### PR TITLE
Update geom-statebins.R

### PR DESCRIPTION
**Pull request by haroldgil**
Removed first '/' in saveRDS(xdat, "/tmp/setupdata.rds"). 
Result: saveRDS(xdat, "tmp/setupdata.rds")

### CODE REVIEW

**Comment by haroldgil** [comment]
Bummer. I don't know how to resolve these test check failures so I'll just leave the PR at this point.

**Comment by hrbrmstr** [comment]
Thx for finding this. That was left in error. I cleaned up this and the theme code so it should work everywhere now (and added Travis checks to be sure). I'm closing this but can you dbl check your attribution in the `DESCRIPTION` file for correctness? If you want more info in it (email) just drop a note here (a PR is fine, too, but it's easy for me to make simple edits too).

https://github.com/hrbrmstr/statebins/blob/master/DESCRIPTION#L13-L14

**Comment by haroldgil** [comment]
I was already listed earlier as a ctb:

person("Harold", "Gil", email = "hgil@marionhealth.org", role = "ctb",
           comment = "fix for show.guide")

You can just update the existing entry to:
person("Harold", "Gil", email = "hgil@marionhealth.org", role = "ctb",
           comment = "fix for show.guide, facet/geom testing & test data fix")

Thanks!
Harold

**Comment by hrbrmstr** [comment]
gosh. I can't even read :-)
(I'm cleaning up a ton of repos and am in "robot" mode)

thx.

**Pull request closed without merging**
